version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ashdb:/var/lib/postgresql/data


  backend:   
    build: 
      context: .
      dockerfile: ./docker/Dockerfile.backend
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_URL=${POSTGRES_URL}
    depends_on:
      - postgres

  frontend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.frontend
      args:
        - POSTGRES_URL=${POSTGRES_URL}

    ports:
      - "3000:3000"

    environment:
      - POSTGRES_URL=${POSTGRES_URL}
    depends_on:
      - postgres



      
  websocket:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.websocket

    ports:
      - "8080:8080"

    environment:
      - POSTGRES_URL=${POSTGRES_URL}
    depends_on:
      - postgres

      

volumes:
  ashdb:
