FROM node:22-alpine

WORKDIR /app

COPY . .

ARG POSTGRES_URL

RUN npm install

RUN npm run prisma
RUN POSTGRES_URL=${POSTGRES_URL} npm run build
EXPOSE 3000

CMD [ "npm","run","frontend" ]

